[tool.poetry]
name = "podfetch"
version = "0.1.0"
description = ""
authors = ["bitesized"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
feedparser = "^6.0.11"
argparse = "^1.4.0"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
